server:
  port: 8166
  servlet:
    context-path: /web-market-cart
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
utils:
  cart:
    prefix: SPRING_WEB_APP_
integrations:
  core-service:
    url: http://localhost:5555/core
  analit-service:
    url: http://localhost:5555/analit
spring:
  kafka:
    consumer:
      group-id: 223
    bootstrap-servers: localhost:9092