server:
  port: 8166
  servlet:
    context-path: /web-market-cart
utils:
  cart:
    prefix: SPRING_WEB_APP_
integrations:
  core-service:
    url: http://localhost:5555/core
  analit-service:
    url: http://localhost:5555/analit